--removing tables
DROP TABLE IF EXISTS Температура CASCADE;
DROP TABLE IF EXISTS Запах CASCADE;
DROP TABLE IF EXISTS Группа_людей CASCADE;
DROP TABLE IF EXISTS Ощущениея CASCADE;
DROP TABLE IF EXISTS Координаты CASCADE;
DROP TABLE IF EXISTS Подземный_ход CASCADE;
DROP TABLE IF EXISTS Соединение_ходов CASCADE;
DROP TABLE IF EXISTS Лагерь CASCADE;
DROP TABLE IF EXISTS Вещь CASCADE;
DROP TABLE IF EXISTS Объект CASCADE;
DROP TABLE IF EXISTS Тип_сущности CASCADE;
DROP TABLE IF EXISTS Нахождение_сущности CASCADE;

--removing domains
DROP DOMAIN IF EXISTS positive_integer CASCADE;
DROP DOMAIN IF EXISTS percentage CASCADE;